apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ceph-secret: {{ .Values.ceph.key | quote }}
  jenkins-token: {{ .Values.jenkins.jenkins_token | b64enc | quote }}
